version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - run: echo "$CACHE_VERSION" > _cache_version

      - restore_cache:
          keys:
          - v{{ checksum "_cache_version" }}-dependencies-{{ checksum "package.json" }}
          - v{{ checksum "_cache_version" }}-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v{{ checksum "_cache_version" }}-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

      - run: npm test:types && npm test:ci --ci --silent
