import { configurePixiReact, PixiComponent } from '@pixi/react-modular';
import { configurePixiReactFiber, configurePixiReactHostConfig } from '@pixi/react-fiber';
import {
    TYPES,
    AppProvider,
    AppConsumer,
    AppContext,
    applyDefaultProps,
    configurePixiReactComponents,
    configurePixiReactStage,
    configurePixiReactRenderAPI,
    eventHandlers,
    useTick,
    useApp,
    withPixiApp,
    withFilters,
} from '@pixi/react-components';

const {
    PixiReactFiber,
    createRoot,
    render,
    unmountComponentAtNode,
    Stage,
} = configurePixiReact({
    configurePixiReactHostConfig,
    configurePixiReactFiber,
    configurePixiReactComponents,
    configurePixiReactStage,
    configurePixiReactRenderAPI,
});

const {
    BitmapText,
    Container,
    Graphics,
    NineSlicePlane,
    ParticleContainer,
    Sprite,
    AnimatedSprite,
    Text,
    TilingSprite,
    SimpleMesh,
    SimpleRope,
} = TYPES;

export {
    PixiComponent,
    PixiReactFiber,
    TYPES,
    BitmapText,
    Container,
    Graphics,
    NineSlicePlane,
    ParticleContainer,
    Sprite,
    AnimatedSprite,
    Text,
    TilingSprite,
    SimpleMesh,
    SimpleRope,
    createRoot,
    render,
    unmountComponentAtNode,
    Stage,
    AppProvider,
    AppConsumer,
    AppContext,
    useTick,
    useApp,
    applyDefaultProps,
    withPixiApp,
    withFilters,
    eventHandlers,
};
